version: '3.8'

services:
  # Development container
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Containerfile
    image: beancount-importers:latest
    volumes:
      - ./:/workspace
      - type: bind
        source: ${GPG_SOCKET_PATH:-/dev/null}
        target: /root/.gnupg/S.gpg-agent
        consistency: delegated
    working_dir: /workspace
    stdin_open: true
    tty: true
